### ISSUE TITLE
Pas de connexion rtorrent et rutorrent

### ISSUE THREAD

**Issue by valounours** [cloneMe/turbo-seedbox#3]
Salut,

Super script seulement j'ai un soucis avec....

rutorrent ne parvient pas à établir de connexion avec rtorrent comment faire ?

Merci, Valentin

**Comment by cloneMe** [comment]
C'est un peu short comme description de problème ;)
Combien as-tu d'utilisateur ? (de ligne dans htpasswd.txt)
Si t'as plusieurs utilisateurs, as tu le problème pour tous ?
En rafraichissant la page, F5, as-tu encore le problème ?
