### ISSUE TITLE
502 Bad gateway pour le service sickrage

### ISSUE THREAD

**Issue by razaborg** [cloneMe/turbo-seedbox#5]
Bonjour,

J'ai relancé le build plusieurs fois, mais à chaque fois j'ai un problème avec sickrage.
J'ai installé uniquement sickrage, rtorrent & couchpotato. Les 2 autres fonctionnent parfaitement.

Quand je tente d'acceder à l'url sickrage.host.tld, j'obtiens une 502 bad gateway. Et quand je vais voir dans les logs du nginx-front, voici ce qu'il me dit : 

````
2017/02/19 12:39:03 [error] 7#0: *87 connect() failed (111: Connection refused) while connecting to upstream, client: 78.120.155.78, server: ~^(sickrage)(\.\w+)+$, request: "GET / HTTP/1.1", upstream: "http://172.18.0.3:20001/", host: "sickrage.host.tld"
````

**Comment by james2001** [comment]
@razaborg c'était quoi ton problème?

**Comment by razaborg** [comment]
Le problème est plutôt explicite, j'ai plus tous les détails en tête. 
Quant à la solution, j'ai simplement utilisé le container linuxserver/sickrage et j'ai fait mon docker-compose moi même.
